name: Build
on: push
env:
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY}}
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Project dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "azure/requirements.txt"

      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov selenium playwright

      - name: Running pytest
        run: |
          pytest -v  --cov --cov-report=xml --cov-report=html --junitxml="xunit-result.xml"

      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: htmlcov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
